preload = /home/evertoncosmo/Pictures/skyline.jpg
wallpaper = ,/home/evertoncosmo/Pictures/skyline.jpg


wallpaper {
    monitor = 
    path = /home/evertoncosmo/Pictures/skyline.jpg
    fit_mode = cover
}
