preload = /home/evertoncosmo/Pictures/a_woman_with_long_hair_wearing_sunglasses.png
wallpaper = ,/home/evertoncosmo/Pictures/a_woman_with_long_hair_wearing_sunglasses.png


wallpaper {
    monitor = 
    path = /home/evertoncosmo/Pictures/a_woman_with_long_hair_wearing_sunglasses.png

    fit_mode = cover
}
