preload = /home/evertoncosmo/Pictures/rad_samurai.jpg
wallpaper = ,/home/evertoncosmo/Pictures/rad_samurai.jpg


wallpaper {
    monitor = 
    path = /home/evertoncosmo/Pictures/rad_samurai.jpg
    fit_mode = cover
}
