################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
monitor =eDP-1, highres, auto, 1

# monitor=,highres,auto,1
monitor=DP-3,highres,0x0, 1, bitdepth, 8, vrr, 2

# xwayland {
#     force_zero_scaling = true
# }
